### ISSUE TITLE
drakma throws low level stream error when transfer interupted by host.

### ISSUE THREAD

**Issue by VrRm** [edicl/drakma#54]
Throwning an error from the underlying stream library is problematic in situations where you're trying to create a reliable service from possibly unreliably HTTP hosts, i.e. reverse proxish type scenario where you made want to retry or select a different backend.  Also it makes using drakma in a testing tool inconvenient.

Maybe something along the lines of the cookie error, where error generation can be optionally suppressed.

```
couldn't read from #<SB-SYS:FD-STREAM
                     for "socket 172.28.12.234:42164, peer: 172.26.27.23:8080"
                     {100A1492B3}>:
  Connection reset by peer
   [Condition of type SB-INT:SIMPLE-STREAM-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] Abort thread (#<THREAD "new-repl-thread" RUNNING {10087C6063}>)

Backtrace:
  0: (SB-IMPL::SIMPLE-STREAM-PERROR "couldn't read from ~S" #<SB-SYS:FD-STREAM for "socket 172.28.12.234:42164, peer: 172.26.27.23:8080" {100A1492B3}> 104)
  1: (SB-IMPL::REFILL-INPUT-BUFFER #<SB-SYS:FD-STREAM for "socket 172.28.12.234:42164, peer: 172.26.27.23:8080" {100A1492B3}>)
  2: (SB-IMPL::INPUT-UNSIGNED-8BIT-BYTE #<SB-SYS:FD-STREAM for "socket 172.28.12.234:42164, peer: 172.26.27.23:8080" {100A1492B3}> NIL :EOF)
  3: (READ-BYTE #<SB-SYS:FD-STREAM for "socket 172.28.12.234:42164, peer: 172.26.27.23:8080" {100A1492B3}> NIL :EOF)
  4: (READ-BYTE #<CHUNGA:CHUNKED-IO-STREAM {100A1493E3}> NIL NIL)
  5: ((:METHOD FLEXI-STREAMS::READ-BYTE* (FLEXI-STREAMS:FLEXI-INPUT-STREAM)) #<unavailable argument>) [fast-method]
  6: ((:METHOD STREAM-READ-BYTE (FLEXI-STREAMS:FLEXI-INPUT-STREAM)) #<unavailable argument>) [fast-method]
  7: ((SB-PCL::EMF STREAM-READ-BYTE) #<unavailable argument> #<unavailable argument> #<FLEXI-STREAMS:FLEXI-IO-STREAM {100A14B523}>)
  8: (READ-BYTE #<FLEXI-STREAMS:FLEXI-IO-STREAM {100A14B523}> NIL NIL)
  9: (CHUNGA:READ-CHAR* #<FLEXI-STREAMS:FLEXI-IO-STREAM {100A14B523}> NIL NIL)
 10: (CHUNGA:READ-LINE* #<FLEXI-STREAMS:FLEXI-IO-STREAM {100A14B523}> #<READABLE-WRITABLE-STREAM {1004473D53}>)
 11: (DRAKMA::READ-STATUS-LINE #<FLEXI-STREAMS:FLEXI-IO-STREAM {100A14B523}> #<READABLE-WRITABLE-STREAM {1004473D53}>)
 12: ((LABELS DRAKMA::FINISH-REQUEST :IN DRAKMA:HTTP-REQUEST) NIL NIL)
 13: (DRAKMA:HTTP-REQUEST #<PURI:URI http://wac-public-m5-fe-2.internal.atlassian.com:8080/press> :ADDITIONAL-HEADERS (("Accept-Language" . "en")))
 14: (GET-MAGNOLIA-PUBLIC-BASE :SCHEME :HTTP :HTTP-HOST "wac-public-m5-fe-2.internal.atlassian.com" :PORT "8080" :LANG :EN :PATH "/press")
 15: (RUN-HTTP-PAGE-TEST ((:LANG . :EN) (:PATH . "/press") (:SCHEME . :HTTP) (:HTTP-HOST . "wac-public-m5-fe-2.internal.atlassian.com") (:PORT . "8080") (:TEST :LQUERY "title")))
 16: ((LAMBDA ()))
 17: (SB-INT:SIMPLE-EVAL-IN-LEXENV (LET ((RESULTS #)) (DOTIMES (I 1000) (PUSH # RESULTS)) RESULTS) #<NULL-LEXENV>)
 18: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SB-INT:QUASIQUOTE (AND #S(SB-IMPL::COMMA :EXPR # :KIND 2))) #<NULL-LEXENV>)
 19: (SB-INT:SIMPLE-EVAL-IN-LEXENV (EVAL (SB-INT:QUASIQUOTE (AND #))) #<NULL-LEXENV>)
 --more--
```

**Comment by hanshuebner** [comment]
I'm unsure what the problem is.  Are you saying that throwing errors is bad
in general, or is it the fact that a usocket error is thrown what you don't
like?  How would the problem be solved if the types of errors that are
thrown would be different?

**Comment by VrRm** [comment]
I guess my primary difficulty was really that I couldn't figure out what errors might be thrown and therefore create appropriate, cross platform, handlers for them.  Python's urllib2 describes possible errors (http and io) as part of the library interface.  Looking at Drakma documentation and code, it wasn't clear how to capture IO or HTTP errors, or even if such things like 404s and aborted connections were errors at all. (Maybe the library just returns an :eof-like value the way the cl stream library can be accessed?)   

Of course it's more than possible that there's a convention in the modern cl io libraries for handling these sorts of things that I'm not aware of.

**Comment by hanshuebner** [comment]
Unfortunately, there is little culture when it comes to specifying the possible conditions that can be raised from a Common Lisp library.  This starts with the spec, in which conditions for library functions are left unspecified and extends throughout the open source library ecosystem.  Given this, I would recommend that you adjust your expectations accordingly and wrap functions that might fail in a catch-all error handler.  You can also turn the thinking upside down in the sense that when calling, say, `DRAKMA:HTTP-REQUEST`, you really don't want to be specific about all the error conditions that can occur, and as such it is fine to have a condition handler just for `ERROR`.

If you need to programmatically react to any particular condition that can occur, you may want to look at `USOCKET` and how it normalizes implementation specific conditions into a common hierarchy.  This will not give you perfect portability (i.e. LispWorks does not use `USOCKET` and some conditions that the implementation raises will not be normalized), but you will at least be in the position to handle "Connection refused" in a different fashion than all other random errors.

Responses sent by the server are not turned into condition by `DRAKMA`.  I would recommend that you write yourself a wrapper around `DRAKMA:HTTP-REQUEST` that implements the behavior expected by your application.
