### ISSUE TITLE
HTTPS breaks in Allegro-CL Express

### ISSUE THREAD

**Issue by criesbeck** [edicl/drakma#73]
Although Allegro supports SSL, the free CL Express does not.

E.g., (drakma:http-request "https://docs-examples.firebaseio.com/rest/quickstart/users.json")  gets an Enterprise SSL not supported error.

Replacing `:allegro` with `(and :allegro (not :allegro-cl-express))` in drakma.asd and util.lisp seemed to fix the problem for me, but I was only able to test with MacOS, since I have a full Allegro on my Windows box

**Comment by hanshuebner** [comment]
Can you submit a pull request?

**Comment by criesbeck** [comment]
First time doing this with a forked repo, so apologies if I did something stupid.
