### ISSUE TITLE
Problems with URL-ENCODE

### ISSUE THREAD

**Issue by otwieracz** [edicl/drakma#78]
The request:
`(drakma:http-request 
"https://foobar.slack.com/api/search.all?query=users&query=\"password\"&token=foobar")`

crashes PURI because of `"` character. This seems valid.

However, the request
`(drakma:http-request 
"https://foobar.slack.com/api/search.all?query=users&query=%22password%22&token=foobar")`

Is being transformed (probably by `drakma:url-encode`) to:
`https://foobar.slack.com/api/search.all?query=users&query=%2522password%2522&token=foobar`

I've workarounded this with `url-encode` modified to skip `%` character:

```(defun drakma-url-encode* (string external-format)
  "Returns a URL-encoded version of the string STRING using the
external format EXTERNAL-FORMAT. Skip #\%."
  (with-output-to-string (out)
    (loop for octet across (drakma::string-to-octets (or string "")
                                                     :external-format external-format)
          for char = (code-char octet)
          do (cond ((or (char<= #\0 char #\9)
                        (char<= #\a char #\z)
                        (char<= #\A char #\Z)
                        (find char "$-_.!*'(),%" :test #'char=))
                    (write-char char out))
                   ((char= char #\Space)
                    (write-char #\+ out))
                   (t (format out "%~2,'0x" (char-code char)))))))

```

But right now I have such a mess here with multiple levels of url-sanitization that I've got a feeling that I am doing something completely wrong.

So, the question.

How to send `"` in URI?

**Comment by hanshuebner** [comment]
Problems with PURI are a long-standing issue with DRAKMA.  We made some attempts to replace PURI with QURI and other libraries, but compatibility concerns held us back.  We did add the `:PRESERVE-URI` keyword parameter (http://weitz.de/drakma/#arg-preserve-uri) to help with cases where PURI fails.  Can you work around your issue using it?

**Comment by otwieracz** [comment]
Seems like it at least prevents the `%25` mess. With this I am able to provide already encoded URL.
