### ISSUE TITLE
http://weitz.de/drakma/ is dead

### ISSUE THREAD

**Issue by phoe** [edicl/drakma#90]
Redirects to http://weitz.de/lisp.html instead.
![zrzut ekranu z 2017-11-29 20-04-48](https://user-images.githubusercontent.com/15045546/33393780-93c09eae-d540-11e7-8a11-0be7a1258ad7.png)

**Comment by stassats** [comment]
See edicl/cl-ppcre#33

**Comment by phoe** [comment]
Fixed now as the above commit is fixed.
